### ISSUE TITLE
Is that possible to load a big model?

### ISSUE THREAD

**Issue by bigcat26** [dmarcos/llama2.c-web#1]
I've tried to run llama.c-web with llama7B, whose model file size is 3 gigabytes.

An error occours after the browser downloaded the model file:

```javascript
llama2c-worker.js:25 Uncaught RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at llama2c-worker.js:25:17
(anonymous) @ llama2c-worker.js:25
```

line 25 points to this code:

```javascript
var contentLength = modelFileRequest.headers.get('Content-Length');
```

Is there any workaround to pass the model file to WASIContext without such a large memory block allocation?

**Comment by dmarcos** [comment]
Sorry. just saw this. You can try increase the memory allocation here:

https://github.com/dmarcos/llama2.c-web/blob/master/llama2c-worker.js#L6

Let me know if it works. 

Also you might be hitting the browser tab memory limit. I believe it's between 2GB-4GB depending on the browser but can't find up to date info. Can you try with a model between 1GB and 2GB to see if that might be the issue?

Best of luck and sorry again for the late reply.

**Comment by bigcat26** [comment]
Thank you for your reply. I had tried modifying the js script before, but it threw malloc failed errors when running. I did a simple test and it seems the model size cannot exceed around 2GB. For now I've put investigating this issue on hold.

**Comment by dmarcos** [comment]
Can you share the model you're trying to load? I can do my own testing. Thanks

**Comment by bigcat26** [comment]
> Can you share the model you're trying to load? I can do my own testing. Thanks

I've tested with the model: [llama-2-7b-chat.ggmlv3.q2_K.bin](https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGML/blob/main/llama-2-7b-chat.ggmlv3.q2_K.bin)
